vas_cov <- read.csv("/Users/kevintang/Library/Mobile Documents/com~apple~CloudDocs/Documents/r_projects/unicef_vasupp/data/vas_6/vas_6_dtp3.csv")
#yes <-vas_cov %>% filter(dtp3_cat=="yes") %>% select(country,vasupp)
#no <-vas_cov %>% filter(dtp3_cat=="no")%>% select(country,vasupp)
#yes <-vas_cov %>% filter(mea_cat=="yes") %>% select(country,vasupp)
#no <-vas_cov %>% filter(mea_cat=="no")%>% select(country,vasupp)
#yes <-vas_cov %>% filter(polio_cat=="yes") %>% select(country,vasupp)
#no <-vas_cov %>% filter(polio_cat=="no")%>% select(country,vasupp)
#yes <-vas_cov %>% filter(res=="urban") %>% select(country,vasupp)
#no <-vas_cov %>% filter(res=="rural")%>% select(country,vasupp)
#yes <-vas_cov %>% filter(sep=="poorest") %>% select(country,vasupp)
#no <-vas_cov %>% filter(sep=="richest")%>% select(country,vasupp)
#yes <-vas_cov %>% filter(dec_cat5=="1") %>% select(country,vasupp)
#no <-vas_cov %>% filter(dec_cat5=="5")%>% select(country,vasupp)
yes <-vas_cov %>% filter(age_cat=="12-35 m") %>% select(country,vasupp)
no <-vas_cov %>% filter(age_cat=="36 -59 m")%>% select(country,vasupp)
vas_cov_order <- merge(x=yes, y=no, by.x='country', by.y='country', fill=-9999, all.x = TRUE)
vas_cov_order$diff <- vas_cov_order$vasupp.x-vas_cov_order$vasupp.y
vas_cov_order_eq <- vas_cov_order %>% filter(diff<0)
vas_cov_order_eq <- vas_cov_order_eq %>%  arrange(vasupp.y) %>% select(country) %>% dplyr::mutate(order = row_number())
vas_cov_order_noeq <- vas_cov_order %>% filter(diff>0)
vas_cov_order_noeq <- vas_cov_order_noeq %>%  arrange(vasupp.y) %>% select(country) %>% dplyr::mutate(order = row_number())
vas_cov_order <-rbind(vas_cov_order_noeq,vas_cov_order_eq)%>% dplyr::mutate(order2 = row_number()) %>% select(-order)

vas_cov <- merge(x=vas_cov, y=vas_cov_order, by.x='country', by.y='country', fill=-9999, all.x = TRUE)
