---
title: "rdhs_vas_age"
author: "Kevin Tang"
date: "9/18/2021"
output: html_document
---

```{r}
library(rdhs)
library(demogsurv)
library(data.table)
library(haven)
pacman::p_load(rio,tidyverse,survey,srvyr,gtsummary,plyr)
options(stringsAsFactors = TRUE)
```

Download the DHS data
```{r}
## set up your credentials
set_rdhs_config(email = "kevin.tang1@student.lshtm.ac.uk",
                password_prompt =  TRUE,
                project = "Micronutrient Action Policy Support Tool", # Put your project name here
                config_path = "rdhs.json",
                global=FALSE)

# we will give our permission here so that we don't have to provide a prompt within the README.
Sys.setenv("rdhs_RENVIRON_PERMISSION"=1)

## a little nugget to return API requests as data.table rather than data.frame.
Sys.setenv(rdhs_DATA_TABLE = "TRUE")

## Identify all DHS surveys for the following countries
countries <- dhs_countries()
cc <- c( "ET","MW","CM","BJ","CF","ML","NP","PK","BU","BD","GM","GN","HT","LB","NG","PG","PH","SN","SL","TJ","TZ","TL","UG","ZM","ZW","ZA")
cc <- c("BF","MD","NI","AF","KH","TD","CG","CD","CI","GH","BO","KM","SZ","KE","LS","MZ","MM","RW","ST","TG","YE","NM", "GA","GU","HN","ID","KY")

# Use rdhs to retreive datasets, downloading them from DHS website if not already in the rdhs cache.
surveys <- dhs_surveys(countryIds = cc, surveyYearStart=2010, surveyType = "DHS")

# Identify births recode (BR) datasets corageponding to these surveys.
step <- dhs_datasets(fileType = "IR", fileFormat = "flat")
ird <- step[which(step$SurveyId %in% surveys$SurveyId),]

# Use rdhs to retreive datasets, downloading them from DHS website if not already in the rdhs cache.
Sys.setenv("rdhs_LOUD_DOWNLOAD" = TRUE)
ird$path <- unlist(get_datasets(ird$FileName,clear_cache = TRUE))
```

Load all of the datasets into R as a list
```{r}
ir <- list()
for(survid in ird$SurveyId){
  print(survid)
  dat <- readRDS(ird[which(ird$SurveyId == survid),]$path)
  dat <- dat[grep("caseid|
                |v001|v005|
                |h34_1|h34_2|h34_3|h34_4|h34_5|h34_6|
                |b8_01|b8_02|b8_03|b8_04|b8_05|b8_06|
                |b19_01|b19_02|b19_03|b19_04|b19_05|b19_06|                
                |v414g|v414h|v414i|v414j|v414k|v414l|v414m|v414n|
                |h3_1|h3_2|h3_3|h3_4|h3_5|h3_6|
                |h7_1|h7_2|h7_3|h7_4|h7_5|h7_6|
                |h9_1|h9_2|h9_3|h9_4|h9_5|h9_6|
                |v106|
                |v102|
                |v190", names(dat))]
  ir[[survid]] <- dat
}

ir <- lapply(ir, haven::as_factor)

##Add survey-level variables
ir <- Map(data.frame,
          SurveyId = surveys$SurveyId,
          CountryName = surveys$CountryName,
          SurveyYear = surveys$SurveyYear,
          ir)

ir <- lapply(ir, function(x){ x$SurveyId <- factor(x$SurveyId) ; return(x)})
ir <- lapply(ir, function(x){ x$CountryName <- factor(x$CountryName) ; return(x)})
ir <- lapply(ir, function(x){ x$SurveyYear <- factor(x$SurveyYear) ; return(x)})
```


#INDEPENDENT COUNTRY COVERAGE
```{r}
#Country by country analysis
data <- ir$ZW2015DHS

#Reformat survey weights
data$v005 <- data$v005/1000000 

c1 <- data %>% dplyr::select(caseid, v001, v005, b8_01, b19_01, h34_1, h3_1)
c2 <- data %>% dplyr::select(caseid, v001, v005, b8_02, b19_02, h34_2, h3_2)
c3 <- data %>% dplyr::select(caseid, v001, v005, b8_03, b19_03, h34_3, h3_3)
c4 <- data %>% dplyr::select(caseid, v001, v005, b8_04, b19_04, h34_4, h3_4)
c5 <- data %>% dplyr::select(caseid, v001, v005, b8_05, b19_05, h34_5, h3_5)
c6 <- data %>% dplyr::select(caseid, v001, v005, b8_06, b19_06, h34_6, h3_6)

names(c1) <- c('caseid', "cluster", "weight", 'age', 'age_m', 'vas', 'dtp1')
names(c2) <- c('caseid', "cluster", "weight", 'age', 'age_m', 'vas', 'dtp1')
names(c3) <- c('caseid', "cluster", "weight", 'age', 'age_m', 'vas', 'dtp1')
names(c4) <- c('caseid', "cluster", "weight", 'age', 'age_m', 'vas', 'dtp1')
names(c5) <- c('caseid', "cluster", "weight", 'age', 'age_m', 'vas', 'dtp1')
names(c6) <- c('caseid', "cluster", "weight", 'age', 'age_m', 'vas', 'dtp1')

data <- rbind(c1,c2,c3,c4,c5,c6)
data <-data %>% filter(age_m>5) %>% filter(age_m<60)

#Recatagorize outcome
data <- data %>% mutate(vasupp = as.factor(case_when(vas=="yes" ~ "yes",
                                           vas=="no" ~ "no")))

data <- data %>% mutate(age_cat = case_when(
                             age == 0  ~ "06-11 m",
                             age == 1 ~ "12-23 m",
                             age == 2 | age ==4  ~ "24-59 m"))

data <- data %>% mutate(dtp1_cat = case_when(dtp1=="vaccination date on card" ~ "yes",
                                           dtp1=="reported by mother" ~ "yes",
                                           dtp1=="vaccination marked on card" ~ "yes",
                                           dtp1=="no" ~ "no"))

#Adjust for DHS weights
w_data <- data %>% as_survey_design(id = cluster, strata =NULL, weights = weight, nest=T)

ZW2015DHS_age <- w_data %>%
  filter(!is.na(age_cat)) %>% 
  srvyr::group_by(age_cat) %>%
  srvyr::summarise(
    vasupp = (survey_mean(vasupp == "yes", proportion = TRUE, vartype = "ci",na.rm = T)) * 100)

ZW2015DHS_dtp1 <- w_data %>%
  filter(!is.na(dtp1_cat)) %>% 
  srvyr::group_by(dtp1_cat) %>%
  srvyr::summarise(
    vasupp = (survey_mean(vasupp == "yes", proportion = TRUE, vartype = "ci",na.rm = T)) * 100)

ZW2015DHS_age$country <- "Zimbabwe"
ZW2015DHS_dtp1$country <- "Zimbabwe"
```

```{r}
vas_cov_age <- rbind(AF2015DHS_age,BD2017DHS_age,BF2010DHS_age,BJ2017DHS_age,BU2016DHS_age,CD2013DHS_age,CG2011DHS_age,CI2012DHS_age,CM2018DHS_age,GA2012DHS_age,GH2014DHS_age,GM2019DHS_age,GN2018DHS_age,GU2015DHS_age,HN2011DHS_age,HT2016DHS_age,IA2012DHS_age,ID2012DHS_age,KE2014DHS_age,KH2014DHS_age,KM2012DHS_age,KY2012DHS_age,LB2019DHS_age,LS2014DHS_age,ML2018DHS_age,MM2016DHS_age,MW2015DHS_age,MZ2011DHS_age,NG2018DHS_age,NI2012DHS_age,NP2016DHS_age,PG2017DHS_age,PH2017DHS_age,PK2017DHS_age,RW2015DHS_age,SL2019DHS_age,SN2018DHS_age,TD2014DHS_age,TG2013DHS_age,TJ2017DHS_age,TL2016DHS_age,TZ2015DHS_age,UG2016DHS_age,YE2013DHS_age,ZM2018DHS_age,ZW2015DHS_age,ZA2016DHS_age,NM2013DHS_age,ET2016DHS_age)

vas_cov_dtp1 <- rbind(AF2015DHS_dtp1,BD2017DHS_dtp1,BF2010DHS_dtp1,BJ2017DHS_dtp1,BU2016DHS_dtp1,CD2013DHS_dtp1,CG2011DHS_dtp1,CI2012DHS_dtp1,CM2018DHS_dtp1,GA2012DHS_dtp1,GH2014DHS_dtp1,GM2019DHS_dtp1,GN2018DHS_dtp1,GU2015DHS_dtp1,HN2011DHS_dtp1,HT2016DHS_dtp1,IA2012DHS_dtp1,ID2012DHS_dtp1,KE2014DHS_dtp1,KH2014DHS_dtp1,KM2012DHS_dtp1,KY2012DHS_dtp1,LB2019DHS_dtp1,LS2014DHS_dtp1,ML2018DHS_dtp1,MM2016DHS_dtp1,MW2015DHS_dtp1,MZ2011DHS_dtp1,NG2018DHS_dtp1,NI2012DHS_dtp1,NP2016DHS_dtp1,PG2017DHS_dtp1,PH2017DHS_dtp1,PK2017DHS_dtp1,RW2015DHS_dtp1,SL2019DHS_dtp1,SN2018DHS_dtp1,TD2014DHS_dtp1,TG2013DHS_dtp1,TJ2017DHS_dtp1,TL2016DHS_dtp1,TZ2015DHS_dtp1,UG2016DHS_dtp1,YE2013DHS_dtp1,ZM2018DHS_dtp1,ZW2015DHS_dtp1,ZA2016DHS_dtp1,NM2013DHS_dtp1,ET2016DHS_dtp1)
```

```{r}
ggplot(vas_cov) + 
  geom_pointrange(aes(x =reorder(country, order), y = vasupp, ymin = vasupp_low, ymax = vasupp_upp, color = age_cat))+ 
  theme_bw() +
  coord_flip(ylim = c(0, 100)) +
  labs(y = "Percentage of children consuming VAS in the prior 6 months",
       x = "Country") +
  scale_y_continuous(breaks = round(seq(min(0), max(100), by = 20),1))+
  theme(plot.caption = element_text(hjust = 1))

#Create order for dumbell plot
order <- vas_cov_dtp1 %>% filter(dtp1_cat=="yes") %>% arrange(vasupp) %>% select(country) %>% dplyr::mutate(order = row_number())
vas_cov_dtp1<- merge(x=vas_cov_dtp1, y=order, by.x='country', by.y='country', fill=-9999, all.x = TRUE)

order <- vas_cov_age %>% filter(age_cat=="12-23 m") %>% arrange(vasupp) %>% select(country) %>% dplyr::mutate(order = row_number())
vas_cov_age<- merge(x=vas_cov_age, y=order, by.x='country', by.y='country', fill=-9999, all.x = TRUE)

write.csv(vas_cov_age, "/Users/kevintang/Library/Mobile Documents/com~apple~CloudDocs/Documents/r_projects/unicef_vasupp/data/vas_6/vas_6_age.csv", row.names=FALSE)
write.csv(vas_cov_dtp1, "/Users/kevintang/Library/Mobile Documents/com~apple~CloudDocs/Documents/r_projects/unicef_vasupp/data/vas_6/vas_6_dtp1.csv", row.names=FALSE)

vas_cov <- read.csv("/Users/kevintang/Library/Mobile Documents/com~apple~CloudDocs/Documents/r_projects/unicef_vasupp/data/vas_age.csv")
vas_cov$age_cat<-as.factor(vas_cov$age_cat)
```

```{r}
#Country by country analysis
data <- ir$ID2012DHS

#Reformat survey weights
data$v005 <- data$v005/1000000 

c1 <- data %>% dplyr::select(caseid, v001, v005, b8_01, h34_1, h3_1)
c2 <- data %>% dplyr::select(caseid, v001, v005, b8_02, h34_2, h3_2)
c3 <- data %>% dplyr::select(caseid, v001, v005, b8_03, h34_3, h3_3)
c4 <- data %>% dplyr::select(caseid, v001, v005, b8_04, h34_4, h3_4)
c5 <- data %>% dplyr::select(caseid, v001, v005, b8_05, h34_5, h3_5)
c6 <- data %>% dplyr::select(caseid, v001, v005, b8_06, h34_6, h3_6)

names(c1) <- c('caseid', "cluster", "weight", 'age', 'vas', 'dtp1')
names(c2) <- c('caseid', "cluster", "weight", 'age', 'vas', 'dtp1')
names(c3) <- c('caseid', "cluster", "weight", 'age', 'vas', 'dtp1')
names(c4) <- c('caseid', "cluster", "weight", 'age', 'vas', 'dtp1')
names(c5) <- c('caseid', "cluster", "weight", 'age', 'vas', 'dtp1')
names(c6) <- c('caseid', "cluster", "weight", 'age', 'vas', 'dtp1')

data <- rbind(c1,c2,c3,c4,c5,c6)
data <-data %>% filter(age<5)

#Recatagorize outcome
#data <- data %>% mutate(vasupp = as.factor(case_when(vas=="yes" ~ "yes",
 #                                          vas=="no" ~ "no")))

data <- data %>% mutate(vasupp = as.factor(case_when(vas=="yes, red" ~ "yes",
                                                     vas=="yes, blue" ~ "yes",
                                           vas=="no" ~ "no")))


data <- data %>% mutate(age_cat = case_when(
                             age == 0  ~ "06-11 m",
                             age == 1 ~ "12-23 m",
                             age == 2 | age ==4  ~ "24-59 m"))

data <- data %>% mutate(dtp1_cat = case_when(dtp1=="vaccination date on card" ~ "yes",
                                           dtp1=="reported by mother" ~ "yes",
                                           dtp1=="vaccination marked on card" ~ "yes",
                                           dtp1=="no" ~ "no"))

#Adjust for DHS weights
w_data <- data %>% as_survey_design(id = cluster, strata =NULL, weights = weight, nest=T)

ID2012DHS_age <- w_data %>%
  filter(!is.na(age_cat)) %>% 
  srvyr::group_by(age_cat) %>%
  srvyr::summarise(
    vasupp = (survey_mean(vasupp == "yes", proportion = TRUE, vartype = "ci",na.rm = T)) * 100)

ID2012DHS_dtp1 <- w_data %>%
  filter(!is.na(dtp1_cat)) %>% 
  srvyr::group_by(dtp1_cat) %>%
  srvyr::summarise(
    vasupp = (survey_mean(vasupp == "yes", proportion = TRUE, vartype = "ci",na.rm = T)) * 100)

ID2012DHS_age$country <- "Indonesia"
ID2012DHS_dtp1$country <- "Indonesia"
```