---
title: "rdhs_vas_vafood"
author: "Kevin Tang"
date: "9/18/2021"
output: html_document
---

```{r}
library(rdhs)
library(demogsurv)
library(data.table)
library(haven)
pacman::p_load(rio,tidyverse,survey,srvyr,gtsummary,plyr)
options(stringsAsFactors = TRUE)
```

Download the DHS data
```{r}
## set up your credentials
set_rdhs_config(email = "kevin.tang1@student.lshtm.ac.uk",
                password_prompt =  TRUE,
                project = "Micronutrient Action Policy Support Tool", # Put your project name here
                config_path = "rdhs.json",
                global=FALSE)

# we will give our permission here so that we don't have to provide a prompt within the README.
Sys.setenv("rdhs_RENVIRON_PERMISSION"=1)

## a little nugget to return API requests as data.table rather than data.frame.
Sys.setenv(rdhs_DATA_TABLE = "TRUE")

## Identify all DHS surveys for the following countries
countries <- dhs_countries()
cc <- c( "ET","MW","CM","BJ","CF","ML","NP","PK","AO","BU","BD","GM","GN","HT","LB","NG","PG","PH","SN","SL","TJ","TZ","TL","UG","ZM","ZW","ZA")
cc <- c("BF","MD","NI","AF","KH","TD","CG","CD","CI","GH","BO","KM","SZ","KE","LS","MZ","MM","RW","ST","TG","YE","GU","HN","ID","JO","KY","NM", "GA")

# Use rdhs to retreive datasets, downloading them from DHS website if not already in the rdhs cache.
surveys <- dhs_surveys(countryIds = cc, surveyYearStart=2005, surveyType = "DHS")

# Identify births recode (BR) datasets corresponding to these surveys.
step <- dhs_datasets(fileType = "IR", fileFormat = "flat")
ird <- step[which(step$SurveyId %in% surveys$SurveyId),]

# Use rdhs to retreive datasets, downloading them from DHS website if not already in the rdhs cache.
Sys.setenv("rdhs_LOUD_DOWNLOAD" = TRUE)
ird$path <- unlist(get_datasets(ird$FileName,clear_cache = TRUE))
```

Load all of the datasets into R as a list
```{r}
ir <- list()
for(survid in ird$SurveyId){
  print(survid)
  dat <- readRDS(ird[which(ird$SurveyId == survid),]$path)
  dat <- dat[grep("caseid|
                |v001|v005|
                |h33_1|h33_2|h33_3|h33_4|h33_5|h33_6|
                |h34_1|h34_2|h34_3|h34_4|h34_5|h34_6|
                |b8_01|b8_02|b8_03|b8_04|b8_05|b8_06|
                |b19_01|b19_02|b19_03|b19_04|b19_05|b19_06|                
                |v414g|v414h|v414i|v414j|v414k|v414l|v414m|v414n|v414q|
                |h7_1|h7_2|h7_3|h7_4|h7_5|h7_6|
                |h9_1|h9_2|h9_3|h9_4|h9_5|h9_6|
                |v106|
                |v102|
                |v190", names(dat))]
  ir[[survid]] <- dat
}

ir <- lapply(ir, haven::as_factor)

##Add survey-level variables
ir <- Map(data.frame,
          SurveyId = surveys$SurveyId,
          CountryName = surveys$CountryName,
          SurveyYear = surveys$SurveyYear,
          ir)

ir <- lapply(ir, function(x){ x$SurveyId <- factor(x$SurveyId) ; return(x)})
ir <- lapply(ir, function(x){ x$CountryName <- factor(x$CountryName) ; return(x)})
ir <- lapply(ir, function(x){ x$SurveyYear <- factor(x$SurveyYear) ; return(x)})
```

#INDEPENDENT COUNTRY COVERAGE
```{r}
#Country by country analysis
data <- ir$YE2013DHS
#Reformat survey weights
data$v005 <- data$v005/1000000 
data <- data %>% filter(b8_01<2)
data <- data %>% mutate(vasupp = h34_1)#Recatagorize outcome
#data <- data %>% mutate(vasupp = case_when(h34_1=="yes, red" ~ "yes",
 #                                          h34_1=="yes, blue" ~ "yes",
  #                                         h34_1=="no" ~ "no",
   #                                        h34_1=="don't know" ~ "don't know",
    #                                       h34_1=="missing" ~ "missing"))

data <- data %>%filter(!is.na(v414i))
data <- data %>% mutate(vafood = ifelse(v414g=="yes" |
                                   v414h=="yes" |
                                   v414i=="yes" |
                                   v414j=="yes" |
                                   v414k=="yes" |
                                   v414l=="yes" |
                                   v414m=="yes" |
                                   v414n=="yes", "yes", "no")) #Recategorise outcome variable

#Adjust for DHS weights
w_data <- data %>% as_survey_design(id = v001, strata =NULL, weights = v005, nest=T)
#Calculate stratified coverage and 95%CI limits 
YE2013DHS_vafood <- w_data %>%
  srvyr::group_by(vafood) %>%
  srvyr::summarise(
    vasupp = (survey_mean(vasupp == "yes", proportion = TRUE, vartype = "ci",na.rm = T)) * 100)

YE2013DHS_vafood$country <- "Yemen"
```

```{r}
ggplot(vas_cov) + 
  geom_pointrange(aes(x =reorder(country, order), y = vasupp, ymin = vasupp_low, ymax = vasupp_upp, color = vafood))+ 
  theme_bw() +
  coord_flip(ylim = c(0, 100)) +
  labs(y = "Percentage of children consuming VAS in the prior 6 months",
       x = "Country",
       caption="*Philippines did not collect dietary data") +
  scale_y_continuous(breaks = round(seq(min(0), max(100), by = 20),1))+
  theme(plot.caption = element_text(hjust = 1))
```

```{r}
vas_cov_vafood <- rbind(AF2015DHS_vafood,BD2017DHS_vafood,BF2010DHS_vafood,BJ2017DHS_vafood,BU2016DHS_vafood,CD2013DHS_vafood,CG2011DHS_vafood,CI2012DHS_vafood,CM2018DHS_vafood,ET2016DHS_vafood,GA2012DHS_vafood,GH2014DHS_vafood,GM2019DHS_vafood,GN2018DHS_vafood,GU2015DHS_vafood,HN2011DHS_vafood,HT2016DHS_vafood,ID2017DHS_vafood,KE2014DHS_vafood,KH2014DHS_vafood,KM2012DHS_vafood,KY2012DHS_vafood,LB2019DHS_vafood,LS2014DHS_vafood,ML2018DHS_vafood,MM2016DHS_vafood,MW2015DHS_vafood,MZ2011DHS_vafood,NG2018DHS_vafood,NI2012DHS_vafood,NP2016DHS_vafood,PG2017DHS_vafood,PK2017DHS_vafood,RW2015DHS_vafood,SL2019DHS_vafood,SN2018DHS_vafood,TD2014DHS_vafood,TG2013DHS_vafood,TJ2017DHS_vafood,TL2016DHS_vafood,TZ2015DHS_vafood,UG2016DHS_vafood,YE2013DHS_vafood,ZM2018DHS_vafood,ZW2015DHS_vafood,ZA2016DHS_vafood,NM2013DHS_vafood)

#Create order for dumbell plot
order <- vas_cov_vafood %>% filter(vafood=="yes") %>% arrange(vasupp) %>% select(country) %>% dplyr::mutate(order = row_number())
vas_cov_vafood<- merge(x=vas_cov_vafood, y=order, by.x='country', by.y='country', fill=-9999, all.x = TRUE)

write.csv(vas_cov_vafood, "/Users/kevintang/Library/Mobile Documents/com~apple~CloudDocs/Documents/r_projects/unicef_vasupp/data/vas_6/vas_6_vafood_2.csv", row.names=FALSE)

```


```{r}
#Country by country analysis
data <- ir$ZW2015DHS
data$v005 <- data$v005/1000000 #Reformat survey weights
data <-data %>% filter(b19_01>5) %>% filter(b19_01<24)
data <- data %>% mutate(vasupp = h34_1)#Recatagorize outcome
data <- data %>%filter(!is.na(v414i))
data <- data %>% mutate(vafood = ifelse(v414g=="yes" |
                                   v414h=="yes" |
                                   v414i=="yes" |
                                   v414j=="yes" |
                                   v414k=="yes" |
                                   v414l=="yes" |
                                   v414m=="yes" |
                                   v414n=="yes", "yes", "no")) #Recategorise outcome variable

#Adjust for DHS weights
w_data <- data %>% as_survey_design(id = v001, strata =NULL, weights = v005, nest=T)
#Calculate stratified coverage and 95%CI limits 
ZW2015DHS_vafood <- w_data %>%
  srvyr::group_by(vafood) %>%
  srvyr::summarise(
    vasupp = (survey_mean(vasupp == "yes", proportion = TRUE, vartype = "ci",na.rm = T)) * 100)

BJ2017DHS_vafood$country <- "Benin"
```